# Generated by Django 3.0.4 on 2020-03-30 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='datetillblock',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
