# Generated by Django 3.0.4 on 2020-03-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_block_datetillblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block',
            new_name='blockperm',
        ),
    ]
