# Generated by Django 3.0.4 on 2020-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200330_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='tempban',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
