# Generated by Django 3.0.4 on 2020-03-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_block_tempban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='datetillblock',
        ),
    ]
