# Generated by Django 3.0.4 on 2020-03-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200322_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
