# Generated by Django 3.0.4 on 2020-03-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_prof_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
