# Generated by Django 3.0.4 on 2020-03-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
