# Generated by Django 3.0.4 on 2020-03-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='code',
        ),
        migrations.AddField(
            model_name='review',
            name='code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Course'),
        ),
    ]
