# Generated by Django 3.0.4 on 2020-03-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200324_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='prof',
        ),
        migrations.AddField(
            model_name='review',
            name='prof',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Prof'),
        ),
    ]
