# Generated by Django 3.0.4 on 2020-03-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200324_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prof',
            old_name='name',
            new_name='profname',
        ),
    ]
