# Generated by Django 3.0.4 on 2020-03-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20200325_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Prof'),
        ),
    ]
