# Generated by Django 3.0.4 on 2020-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(null=True),
        ),
    ]
