# Generated by Django 3.0.4 on 2020-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_review_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
