# Generated by Django 3.0.4 on 2020-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20200325_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='anonymous',
            field=models.NullBooleanField(default=False),
        ),
    ]
