# Generated by Django 3.0.4 on 2020-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20200325_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
