# Generated by Django 3.0.4 on 2020-03-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
