# Generated by Django 3.0.4 on 2020-03-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_delete_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
